### PR TITLE
Fix #238

### LINKED ISSUE #238: Numeric conversion doesn't fail if number is out of bounds
Say a Lua binding in C# takes a parameter of type byte:

```csharp
void MyFunction(byte i)
{
}
```

Since numbers in Lua are all doubles, MoonSharp attempts a conversion from double to byte. It does this by simply type casting one type to another. This doesn't work because if the value passed in Lua is out of bounds for a byte, say:

```lua
MyFunction(300) -- Lua call to MyFunction with value '300', which is out of range for a byte (0-255)
```

Then it will overflow and the value you get in C# will lead to unexpected behaviour. Instead, numeric conversion should fail in the case the value is out of bounds.

### PR DESCRIPTION
**Pull request by ixjf**

### CODE REVIEW

**Comment by captkirk88** [comment]
@xanathar please pull some of these into the master, people are helping to fix the broken things in your repo

**Comment by ixjf** [comment]
I've tried alerting him before. I think your best bet is contacting him via Twitter. I don't have Twitter, though, and can't be arsed to create one just to get his attention.

**Comment by LimpingNinja** [comment]
Hey all, we have a Discord now and Xan is looking at pulling some people in to help on triaging the pull requests and issues. Hopefully soon, now :-)

**Comment by xanathar** [comment]
Merged. (manually)

**Pull request merged**
